version: '3'

services:

    app:
      build: .
      container_name: app
      volumes:
        - .:/var/www
      depends_on:
          - db
          - redis
      networks:
        - app-network

    nginx:
      build: .docker/nginx
      container_name: nginx
      restart: always
      tty: true
      depends_on:
          - app
      ports:
        - "8000:80"
      volumes:
        - .:/var/www
      networks:
        - app-network

    redis:
        image: redis:alpine
        container_name: redis
        expose:
          - 6379
        networks:
        - app-network

    db:
      image: mysql:5.7
      command: --innodb-use-native-aio=0
      container_name: db
      restart: always
      tty: true
      ports:
          - "33006:3306"
      volumes:
          - ./.docker/db/data:/var/lib/mysql
          - ./.docker/mysql:/docker-entrypoint-initdb.d
      environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_USER=root
      networks:
          - app-network


networks:
  app-network:
      driver: bridge
