apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis-laravel
spec:
 template:
    metadata:
      labels:
        app: redis-laravel
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
             