apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql-server
spec:  # especificação deployment
  replicas: 1
  
  selector:  # selector utilizado na criação do service
    matchLabels:
      app: mysql-server
      tier: db

  template: # referente ao POD
    metadata:
      labels:
        app: mysql-server
        tier: db
    spec: # spec POD 
      containers:
      - image: mysql:5.7
        name: mysql-server
        args:
          - "--ignore-db-dir=lost+found"

        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key:  password

        ports:
        - containerPort: 3306  

        volumeMounts: #moda o volume efetivamente
        - name: mysql-persisntent-storage
          mountPath: /var/lib/mysql
      
      volumes: 
      - name: mysql-persisntent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
