apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-laravel
spec:
 template:
    metadata:
      labels:
        app: app-laravel
    spec:
      containers:
      - name: app
        image: img-app-deployment
        ports:
        - containerPort: 80

        env: 
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key:  password             

        envFrom:
        - configMapRef:
            name: app-conf

        volumeMounts:
        - name: app-conf
          mountPath: /var/www/.env
          subPath: .env


      volumes:
      - name: app-conf
        configMap:
          name: app-config  
          items:  
            - key: env
              path: .env
