apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-laravel
spec:
 template:
    metadata:
      labels:
        app: app-laravel
    spec:
      containers:
      - name: app
        image: img-app-deployment
        command: ["/bin/sh", "-c", "ln -s /var/www /usr/share/nginx; php-fpm;"]
        ports:
        - containerPort: 80

        env: 
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key:  password             

        envFrom:
        - configMapRef:
            name: app-config

        volumeMounts:
        - name: app-config
          mountPath: /var/www/.env
          subPath: .env


      volumes:
      - name: app-config
        configMap:
          name: app-config  
          items:  
            - key: env
              path: .env
